import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet'
import { Skeleton } from '@/components/ui/skeleton'
import { Edit2, GripVertical, Lightbulb, Plus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { useServerFn } from '@tanstack/react-start'
import { plannerIdeasRead } from './planner-schedule-read.api'
import { plannerIdeasUpdate } from './planner-ideas-update.api'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'

export function PlannerIdeas() {
  const [sheetOpen, setSheetOpen] = useState(false)
  const [idea, setIdea] = useState({ title: '', context: '' })

  const plannerIdeasReadFn = useServerFn(plannerIdeasRead)
  const plannerIdeasUpdateFn = useServerFn(plannerIdeasUpdate)
  const queryClient = useQueryClient()

  const { data: ideas = [], isPending } = useQuery({
    queryKey: ['planner-ideas'],
    queryFn: () => plannerIdeasReadFn(),
  })

  const plannerIdeasMutation = useMutation({
    mutationFn: async (data: { title: string; context: string }) => {
      await plannerIdeasUpdateFn({ data })
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['planner-ideas'] })
      setSheetOpen(false)
      setIdea({ title: '', context: '' })
    },
  })

  if (isPending) {
    return (
      <div className="pb-6">
        <div className="flex flex-row items-start justify-between gap-4 mb-6">
          <div className="flex flex-col gap-2">
            <Skeleton className="h-6 w-32" />
            <Skeleton className="h-4 w-48" />
          </div>
          <Skeleton className="h-9 w-9" />
        </div>
        <div className="space-y-3">
          {[1, 2, 3].map((i) => (
            <div key={i} className="flex items-start gap-4 p-4 border rounded-lg">
              <Skeleton className="w-5 h-5 mt-1" />
              <div className="flex-1 space-y-2">
                <Skeleton className="h-4 w-3/4" />
                <Skeleton className="h-3 w-full" />
                <Skeleton className="h-3 w-1/2" />
              </div>
              <div className="flex gap-1">
                <Skeleton className="w-8 h-8" />
                <Skeleton className="w-8 h-8" />
              </div>
            </div>
          ))}
        </div>
      </div>
    )
  }

  return (
    <div className="pb-6">
      <div className="flex flex-row items-start justify-between gap-4">
        <div className="flex flex-col">
          <div className="flex items-center gap-x-2 text-xl font-semibold">
            <Lightbulb className="w-5 h-5" /> Ideas Queue
          </div>
          <div className="subtitle">The first idea is next to be generated by the AI</div>
        </div>
        <Button onClick={() => setSheetOpen(true)}>
          <Plus className="w-4 h-4" />
        </Button>
      </div>

      <div className="mt-6">
        {ideas.length === 0 ? (
          <div className="text-center py-16 text-muted-foreground">
            <p className="text-lg font-medium mb-1">No ideas yet</p>
            <p className="text-sm">Add your first idea to get started with auto-publishing!</p>
          </div>
        ) : (
          <div className="space-y-3">
            {ideas.map((idea) => (
              <div
                key={idea.id}
                className="group flex items-start gap-4 p-4 border rounded-lg hover:border-border/80 transition-colors"
              >
                <GripVertical className="w-5 h-5 text-muted-foreground mt-1 cursor-grab opacity-50 group-hover:opacity-100" />

                <div className="flex-1 min-w-0 space-y-2">
                  <div className="truncate line-clamp-1">{idea.title || 'No title, AI generate one for you.'}</div>
                  <div className="text-sm text-muted-foreground line-clamp-2">
                    {idea.context || 'No additional context'}
                  </div>

                  <div className="text-xs text-muted-foreground">Scheduled for Mon 12 Feb 2025 at 9:00 AM</div>
                </div>

                <div className="flex gap-1 shrink-0">
                  <Button variant="ghost" size="icon">
                    <Edit2 className="w-4 h-4" />
                  </Button>
                  <Button variant="ghost" size="icon">
                    <Trash2 className="w-4 h-4 text-destructive" />
                  </Button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
      <Sheet open={sheetOpen} onOpenChange={setSheetOpen}>
        <SheetContent side="right" className="w-full sm:max-w-lg">
          <SheetHeader>
            <SheetTitle>Queue Article Idea</SheetTitle>
            <SheetDescription>
              Add an idea to the auto-publish queue. AI will write and publish it at the scheduled time.
            </SheetDescription>
          </SheetHeader>

          <div className="space-y-6 py-6 px-4">
            <div className="space-y-2">
              <Label htmlFor="ai-subject">Article Subject</Label>
              <Input
                id="ai-subject"
                placeholder="Leave empty to let AI generate a title"
                value={idea.title}
                onChange={(e) => setIdea({ ...idea, title: e.target.value })}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="ai-additional">Additional Information</Label>
              <Textarea
                id="ai-additional"
                placeholder="Describe the article topic, desired tone (e.g., professional, casual), key points to cover, target audience, and any specific guidelines..."
                className="min-h-[150px]"
                value={idea.context}
                onChange={(e) => setIdea({ ...idea, context: e.target.value })}
              />
            </div>
            <Button
              className="w-full gap-2 cursor-pointer"
              onClick={() => plannerIdeasMutation.mutate(idea)}
              disabled={plannerIdeasMutation.isPending || !idea.context.trim()}
            >
              Add to Queue
            </Button>
          </div>
        </SheetContent>
      </Sheet>
    </div>
  )
}
