services:
  app:
    build: .
    container_name: blogai_app
    env_file:
      - .env
    ports:
      - '80:3000'
    depends_on:
      - blogdb
    restart: unless-stopped
    networks:
      - dokploy-network

  blogdb:
    image: postgres:16.10-alpine3.22
    container_name: blogai_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - dokploy-network

volumes:
  db_data:
