/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogRouteRouteImport } from './routes/_blog/route'
import { Route as BlogIndexRouteImport } from './routes/_blog/index'
import { Route as AdminSignUpRouteImport } from './routes/admin/sign-up'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as BlogAboutRouteImport } from './routes/_blog/about'
import { Route as AdminLayoutRouteRouteImport } from './routes/admin/_layout/route'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as BlogSlugIndexRouteImport } from './routes/_blog/$slug/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminLayoutSettingsIndexRouteImport } from './routes/admin/_layout/settings/index'
import { Route as AdminLayoutPlannerIndexRouteImport } from './routes/admin/_layout/planner/index'
import { Route as AdminLayoutCalendarIndexRouteImport } from './routes/admin/_layout/calendar/index'
import { Route as AdminLayoutArticlesIndexRouteImport } from './routes/admin/_layout/articles/index'
import { Route as AdminLayoutAnalyticsIndexRouteImport } from './routes/admin/_layout/analytics/index'
import { Route as AdminLayoutSettingsGalleryIndexRouteImport } from './routes/admin/_layout/settings/gallery/index'
import { Route as AdminLayoutSettingsAiIndexRouteImport } from './routes/admin/_layout/settings/ai/index'
import { Route as AdminLayoutSettingsAboutIndexRouteImport } from './routes/admin/_layout/settings/about/index'
import { Route as AdminLayoutArticlesCreateIndexRouteImport } from './routes/admin/_layout/articles/create/index'
import { Route as AdminLayoutArticlesArticleIdEditIndexRouteImport } from './routes/admin/_layout/articles/$articleId/edit/index'

const AdminRouteImport = createFileRoute('/admin')()

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/_blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const AdminSignUpRoute = AdminSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const BlogAboutRoute = BlogAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => BlogRouteRoute,
} as any)
const AdminLayoutRouteRoute = AdminLayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRouteRoute,
} as any)
const BlogSlugIndexRoute = BlogSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutSettingsIndexRoute =
  AdminLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AdminLayoutRouteRoute,
  } as any)
const AdminLayoutPlannerIndexRoute = AdminLayoutPlannerIndexRouteImport.update({
  id: '/planner/',
  path: '/planner/',
  getParentRoute: () => AdminLayoutRouteRoute,
} as any)
const AdminLayoutCalendarIndexRoute =
  AdminLayoutCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AdminLayoutRouteRoute,
  } as any)
const AdminLayoutArticlesIndexRoute =
  AdminLayoutArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => AdminLayoutRouteRoute,
  } as any)
const AdminLayoutAnalyticsIndexRoute =
  AdminLayoutAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AdminLayoutRouteRoute,
  } as any)
const AdminLayoutSettingsGalleryIndexRoute =
  AdminLayoutSettingsGalleryIndexRouteImport.update({
    id: '/settings/gallery/',
    path: '/settings/gallery/',
    getParentRoute: () => AdminLayoutRouteRoute,
  } as any)
const AdminLayoutSettingsAiIndexRoute =
  AdminLayoutSettingsAiIndexRouteImport.update({
    id: '/settings/ai/',
    path: '/settings/ai/',
    getParentRoute: () => AdminLayoutRouteRoute,
  } as any)
const AdminLayoutSettingsAboutIndexRoute =
  AdminLayoutSettingsAboutIndexRouteImport.update({
    id: '/settings/about/',
    path: '/settings/about/',
    getParentRoute: () => AdminLayoutRouteRoute,
  } as any)
const AdminLayoutArticlesCreateIndexRoute =
  AdminLayoutArticlesCreateIndexRouteImport.update({
    id: '/articles/create/',
    path: '/articles/create/',
    getParentRoute: () => AdminLayoutRouteRoute,
  } as any)
const AdminLayoutArticlesArticleIdEditIndexRoute =
  AdminLayoutArticlesArticleIdEditIndexRouteImport.update({
    id: '/articles/$articleId/edit/',
    path: '/articles/$articleId/edit/',
    getParentRoute: () => AdminLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminLayoutRouteRouteWithChildren
  '/about': typeof BlogAboutRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sign-up': typeof AdminSignUpRoute
  '/': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug': typeof BlogSlugIndexRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/admin/analytics': typeof AdminLayoutAnalyticsIndexRoute
  '/admin/articles': typeof AdminLayoutArticlesIndexRoute
  '/admin/calendar': typeof AdminLayoutCalendarIndexRoute
  '/admin/planner': typeof AdminLayoutPlannerIndexRoute
  '/admin/settings': typeof AdminLayoutSettingsIndexRoute
  '/admin/articles/create': typeof AdminLayoutArticlesCreateIndexRoute
  '/admin/settings/about': typeof AdminLayoutSettingsAboutIndexRoute
  '/admin/settings/ai': typeof AdminLayoutSettingsAiIndexRoute
  '/admin/settings/gallery': typeof AdminLayoutSettingsGalleryIndexRoute
  '/admin/articles/$articleId/edit': typeof AdminLayoutArticlesArticleIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminLayoutIndexRoute
  '/about': typeof BlogAboutRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sign-up': typeof AdminSignUpRoute
  '/': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug': typeof BlogSlugIndexRoute
  '/admin/analytics': typeof AdminLayoutAnalyticsIndexRoute
  '/admin/articles': typeof AdminLayoutArticlesIndexRoute
  '/admin/calendar': typeof AdminLayoutCalendarIndexRoute
  '/admin/planner': typeof AdminLayoutPlannerIndexRoute
  '/admin/settings': typeof AdminLayoutSettingsIndexRoute
  '/admin/articles/create': typeof AdminLayoutArticlesCreateIndexRoute
  '/admin/settings/about': typeof AdminLayoutSettingsAboutIndexRoute
  '/admin/settings/ai': typeof AdminLayoutSettingsAiIndexRoute
  '/admin/settings/gallery': typeof AdminLayoutSettingsGalleryIndexRoute
  '/admin/articles/$articleId/edit': typeof AdminLayoutArticlesArticleIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_blog': typeof BlogRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRouteRouteWithChildren
  '/_blog/about': typeof BlogAboutRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sign-up': typeof AdminSignUpRoute
  '/_blog/': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_blog/$slug/': typeof BlogSlugIndexRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/admin/_layout/analytics/': typeof AdminLayoutAnalyticsIndexRoute
  '/admin/_layout/articles/': typeof AdminLayoutArticlesIndexRoute
  '/admin/_layout/calendar/': typeof AdminLayoutCalendarIndexRoute
  '/admin/_layout/planner/': typeof AdminLayoutPlannerIndexRoute
  '/admin/_layout/settings/': typeof AdminLayoutSettingsIndexRoute
  '/admin/_layout/articles/create/': typeof AdminLayoutArticlesCreateIndexRoute
  '/admin/_layout/settings/about/': typeof AdminLayoutSettingsAboutIndexRoute
  '/admin/_layout/settings/ai/': typeof AdminLayoutSettingsAiIndexRoute
  '/admin/_layout/settings/gallery/': typeof AdminLayoutSettingsGalleryIndexRoute
  '/admin/_layout/articles/$articleId/edit/': typeof AdminLayoutArticlesArticleIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/about'
    | '/admin/login'
    | '/admin/sign-up'
    | '/'
    | '/api/auth/$'
    | '/$slug'
    | '/admin/'
    | '/admin/analytics'
    | '/admin/articles'
    | '/admin/calendar'
    | '/admin/planner'
    | '/admin/settings'
    | '/admin/articles/create'
    | '/admin/settings/about'
    | '/admin/settings/ai'
    | '/admin/settings/gallery'
    | '/admin/articles/$articleId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/about'
    | '/admin/login'
    | '/admin/sign-up'
    | '/'
    | '/api/auth/$'
    | '/$slug'
    | '/admin/analytics'
    | '/admin/articles'
    | '/admin/calendar'
    | '/admin/planner'
    | '/admin/settings'
    | '/admin/articles/create'
    | '/admin/settings/about'
    | '/admin/settings/ai'
    | '/admin/settings/gallery'
    | '/admin/articles/$articleId/edit'
  id:
    | '__root__'
    | '/_blog'
    | '/admin'
    | '/admin/_layout'
    | '/_blog/about'
    | '/admin/login'
    | '/admin/sign-up'
    | '/_blog/'
    | '/api/auth/$'
    | '/_blog/$slug/'
    | '/admin/_layout/'
    | '/admin/_layout/analytics/'
    | '/admin/_layout/articles/'
    | '/admin/_layout/calendar/'
    | '/admin/_layout/planner/'
    | '/admin/_layout/settings/'
    | '/admin/_layout/articles/create/'
    | '/admin/_layout/settings/about/'
    | '/admin/_layout/settings/ai/'
    | '/admin/_layout/settings/gallery/'
    | '/admin/_layout/articles/$articleId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_blog': {
      id: '/_blog'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_blog/': {
      id: '/_blog/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/admin/sign-up': {
      id: '/admin/sign-up'
      path: '/sign-up'
      fullPath: '/admin/sign-up'
      preLoaderRoute: typeof AdminSignUpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_blog/about': {
      id: '/_blog/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof BlogAboutRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/_blog/$slug/': {
      id: '/_blog/$slug/'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof BlogSlugIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/settings/': {
      id: '/admin/_layout/settings/'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutSettingsIndexRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/planner/': {
      id: '/admin/_layout/planner/'
      path: '/planner'
      fullPath: '/admin/planner'
      preLoaderRoute: typeof AdminLayoutPlannerIndexRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/calendar/': {
      id: '/admin/_layout/calendar/'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminLayoutCalendarIndexRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/articles/': {
      id: '/admin/_layout/articles/'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminLayoutArticlesIndexRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/analytics/': {
      id: '/admin/_layout/analytics/'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminLayoutAnalyticsIndexRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/settings/gallery/': {
      id: '/admin/_layout/settings/gallery/'
      path: '/settings/gallery'
      fullPath: '/admin/settings/gallery'
      preLoaderRoute: typeof AdminLayoutSettingsGalleryIndexRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/settings/ai/': {
      id: '/admin/_layout/settings/ai/'
      path: '/settings/ai'
      fullPath: '/admin/settings/ai'
      preLoaderRoute: typeof AdminLayoutSettingsAiIndexRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/settings/about/': {
      id: '/admin/_layout/settings/about/'
      path: '/settings/about'
      fullPath: '/admin/settings/about'
      preLoaderRoute: typeof AdminLayoutSettingsAboutIndexRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/articles/create/': {
      id: '/admin/_layout/articles/create/'
      path: '/articles/create'
      fullPath: '/admin/articles/create'
      preLoaderRoute: typeof AdminLayoutArticlesCreateIndexRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
    '/admin/_layout/articles/$articleId/edit/': {
      id: '/admin/_layout/articles/$articleId/edit/'
      path: '/articles/$articleId/edit'
      fullPath: '/admin/articles/$articleId/edit'
      preLoaderRoute: typeof AdminLayoutArticlesArticleIdEditIndexRouteImport
      parentRoute: typeof AdminLayoutRouteRoute
    }
  }
}

interface BlogRouteRouteChildren {
  BlogAboutRoute: typeof BlogAboutRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogSlugIndexRoute: typeof BlogSlugIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogAboutRoute: BlogAboutRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogSlugIndexRoute: BlogSlugIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

interface AdminLayoutRouteRouteChildren {
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
  AdminLayoutAnalyticsIndexRoute: typeof AdminLayoutAnalyticsIndexRoute
  AdminLayoutArticlesIndexRoute: typeof AdminLayoutArticlesIndexRoute
  AdminLayoutCalendarIndexRoute: typeof AdminLayoutCalendarIndexRoute
  AdminLayoutPlannerIndexRoute: typeof AdminLayoutPlannerIndexRoute
  AdminLayoutSettingsIndexRoute: typeof AdminLayoutSettingsIndexRoute
  AdminLayoutArticlesCreateIndexRoute: typeof AdminLayoutArticlesCreateIndexRoute
  AdminLayoutSettingsAboutIndexRoute: typeof AdminLayoutSettingsAboutIndexRoute
  AdminLayoutSettingsAiIndexRoute: typeof AdminLayoutSettingsAiIndexRoute
  AdminLayoutSettingsGalleryIndexRoute: typeof AdminLayoutSettingsGalleryIndexRoute
  AdminLayoutArticlesArticleIdEditIndexRoute: typeof AdminLayoutArticlesArticleIdEditIndexRoute
}

const AdminLayoutRouteRouteChildren: AdminLayoutRouteRouteChildren = {
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
  AdminLayoutAnalyticsIndexRoute: AdminLayoutAnalyticsIndexRoute,
  AdminLayoutArticlesIndexRoute: AdminLayoutArticlesIndexRoute,
  AdminLayoutCalendarIndexRoute: AdminLayoutCalendarIndexRoute,
  AdminLayoutPlannerIndexRoute: AdminLayoutPlannerIndexRoute,
  AdminLayoutSettingsIndexRoute: AdminLayoutSettingsIndexRoute,
  AdminLayoutArticlesCreateIndexRoute: AdminLayoutArticlesCreateIndexRoute,
  AdminLayoutSettingsAboutIndexRoute: AdminLayoutSettingsAboutIndexRoute,
  AdminLayoutSettingsAiIndexRoute: AdminLayoutSettingsAiIndexRoute,
  AdminLayoutSettingsGalleryIndexRoute: AdminLayoutSettingsGalleryIndexRoute,
  AdminLayoutArticlesArticleIdEditIndexRoute:
    AdminLayoutArticlesArticleIdEditIndexRoute,
}

const AdminLayoutRouteRouteWithChildren =
  AdminLayoutRouteRoute._addFileChildren(AdminLayoutRouteRouteChildren)

interface AdminRouteChildren {
  AdminLayoutRouteRoute: typeof AdminLayoutRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSignUpRoute: typeof AdminSignUpRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRouteRoute: AdminLayoutRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminSignUpRoute: AdminSignUpRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  BlogRouteRoute: BlogRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
